services:
  
  #mailhog
  mailhog:
    image: 42bv/mailhog:${MAILHOG_VERSION:-latest}
    container_name: ${MAILHOG_NAME:-latest}
    restart: unless-stopped
    networks:
      - tools-network
    ports:
      - ${MAILHOG_SMTP_PORT:-587}:587
      - ${MAILHOG_UI_PORT:-8025}:8025
    volumes:
      - ${MAILHOG_DATA_VOLUME:-./mailhog-data}:/srv/Maildir

  # keycloack
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-24.0}
    container_name: ${KEYCLOAK_NAME:-keycloak}
    restart: unless-stopped
    networks:
      - tools-network
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: ${KEYCLOAK_HTTP_PORT:-7080}
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    # healthcheck:
    #   test:
    #     - CMD
    #     - curl
    #     - -f
    #     - http://0.0.0.0:${KEYCLOAK_HTTP_PORT:-7080}/realms/master
    #   retries: 3
    #   timeout: 5s
    #   interval: 15s
    command: ["start-dev", "--http-port", "${KEYCLOAK_HTTP_PORT:-7080}", "--https-port", "${KEYCLOAK_HTTPS_PORT:-7443}"]
    ports:
      - ${KEYCLOAK_HTTP_PORT:-7080}:7080
      - ${KEYCLOAK_HTTPS_PORT:-7443}:7443
    volumes:
      - ${KEYCLOAK_DATA_VOLUME:-./data/keycloak/data}:/data
      - ${KEYCLOAK_PROVIDER_VOLUME:-./data/keycloak/providers}:/opt/jboss/keycloak/providers
      - ${KEYCLOAK_CONFIG_VOLUME:-./data/keycloak/configuration}:/opt/jboss/keycloak/standalone/configuration

  # minio s3 bucket
  minio:
    container_name: ${MINIO_NAME:-minio-s3}
    image: minio/minio:${MINIO_VERSION:-latest}
    restart: unless-stopped
    networks:
      - tools-network
    ports:
        - ${MINIO_FORWARD_PORT:-9000}:9000
        - ${MINIO_CONSOLE_FORWARD_PORT:-8900}:8900
    environment:
        MINIO_ROOT_USER: ${MINIO_ROOT_USER:-root}
        MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    volumes:
        - ${MINIO_DATA_VOLUME:-./minio-data}:/data
    command: minio server /data/minio --console-address ":${MINIO_CONSOLE_FORWARD_PORT}"
    healthcheck:
        test:
            - CMD
            - curl
            - -f
            - http://0.0.0.0:${MINIO_FORWARD_PORT}/minio/health/live
        retries: 3
        timeout: 5s

  # nginx proxy manager
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:${NGINX_PM_VERSION:-latest}
    container_name: ${NGINX_PM_NAME:-nginx-proxy-manager}
    restart: unless-stopped
    networks:
      - tools-network
    ports:
      - ${NGINX_PM_HTTP_PORT:-80}:80 # Public HTTP Port
      - ${NGINX_PM_HTTPS_PORT:-443}:443 # Public HTTPS Port
      - ${NGINX_PM_ADMIN_WEB_PORT:-81}:81 # Admin Web Port
      # - ${NGINX_PM_FTP_PORT:-21}:21 # FTP
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

    volumes:
      - ${NGINX_PM_DATA_VOLUME:-./nginx-proxy-manager}:/data
      - ${NGINX_PM_SSL_DATA_VOLUME:-./letsencrypt}:/etc/letsencrypt

volumes:
  mailhog-data:
  minio-data:
  nginx-proxy-manager:
  letsencrypt:
   
networks:
  tools-network:
    driver: bridge