version: '3.8'

services:

  mongodb:
    image: mongo:${MONGODB_VERSION:-latest}
    container_name: ${MONGODB_NAME:-mongodb}
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
    ports:
      - ${MONGODB_FORWARD_PORT:-27017}:27017
    volumes:
      - ${MONGODB_DATA_VOLUME:-./mongodb-data}:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 20s
      retries: 10
  
  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_VERSION:-latest}
    container_name: ${MONGO_EXPRESS_NAME:-mongo-express}
    restart: unless-stopped
    ports:
      - ${MONGO_EXPRESS_FORWARD_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_ROOT_USERNAME:-root}:${MONGODB_ROOT_PASSWORD:-password}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_BASIC_AUTH_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_BASIC_AUTH_PASSWORD:-strongpassword}
      ME_CONFIG_BASICAUTH: ${MONGO_EXPRESS_CONFIG_BASICAUTH:-false}
    volumes:
      - ${MONGO_EXPRESS_DATA_VOLUME:-./mongo-express-data}:/config

volumes:
  mongodb-data:
  mongo-express-data:
