version: '3.8'

services:
  # grafana
  grafana:
    image: grafana/grafana:${GF_VERSION:-latest}
    container_name: ${GF_NAME:-grafana}
    restart: unless-stopped
    ports:
      - ${GF_FORWARD_PORT:-5000}:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ${GF_SECURITY_ADMIN_PASSWORD:-./grafana-data}:/var/lib/grafana

  # prometheus
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: ${PROMETHEUS_NAME:-prometheus}
    restart: unless-stopped
    ports:
      - ${PROMETHEUS_FORWARD_PORT:-9090}:9090
    volumes:
      - ${PROMETHEUS_DATA_VOLUME:-./prometheus-data}:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  grafana-data:
  prometheus-data: